using Platform.Application.Interfaces;
using Platform.Application.Services;
using Platform.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Platform.Infrastructure.Data;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();
builder.Services.AddControllers();
// builder.Services.AddSingleton<IDeviceRepository, InMemoryDeviceRepository>();
builder.Services.AddScoped<IDeviceRepository, PostGresDeviceRepository>();
builder.Services.AddScoped<IDeviceService, DeviceService>();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddDbContext<PlatformDbContext>(options =>
    options.UseNpgsql(
        builder.Configuration.GetConnectionString("DefaultConnection")));


var app = builder.Build();

// Configure the HTTP request pipeline.
// if (app.Environment.IsDevelopment())
// {
//     app.MapOpenApi();
// }

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi(); // This serves the raw JSON at /openapi/v1.json

    // Add this to enable the interactive visual UI page
    app.UseSwaggerUI(options =>
    {
        // Points Swagger UI to the JSON file generated by MapOpenApi
        options.SwaggerEndpoint("/openapi/v1.json", "EEAiX API v1");
    });
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
